spring:
  application:
    name: Demo
  datasource:
    url: jdbc:postgresql://localhost:5432/demo?autoReconnect=true
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    user:
      name: admin
      password: admin
server:
  port: 8080
  servlet:
    context-path: /api/v1
jwt:
  signerKey: kzhyJWQwE95cH1ALeaJTZ+5g5neFudCOpO1KygO71FLauVPsxbZv7ihifspQgPP0
springdoc:
  api-docs:
    path: /api-docs
