spring:
  application:
    name: Demo
  datasource:
    url: jdbc:postgresql://localhost:5432/demo?autoReconnect=true
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    user:
      name: admin
      password: admin
  mail:
    from: lovetruongan@gmail.com
    host: smtp.gmail.com
    port: 587
    username: lovetruongan
    password: zfoqktrvqnwwelda
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            required: true
          ssl:
            trust: smtp.gmail.com

outbound:
  identity:
    client-id: "385323340273-id3ii02dd0h0oub9h6mmu1ajj2dvroil.apps.googleusercontent.com"
    client-secret: "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"
    redirect-uri: "http://localhost:5173/authentication"
    default-password: "123456"
    default-birth: "2003-01-05"

server:
  port: 8080
  servlet:
    context-path: /api/v1
jwt:
  signerKey: kzhyJWQwE95cH1ALeaJTZ+5g5neFudCOpO1KygO71FLauVPsxbZv7ihifspQgPP0
springdoc:
  api-docs:
    path: /api-docs
